---
- hosts: debian
  become: sudo
  user: root
  tasks:
    - name: Install Nginx
      apt: pkg=nginx state=latest update_cache=true
      register: nginxlatest
      notify:
       - Start Nginx

  handlers:
    - name: Start Nginx
      service: name=nginx state=started

    - name: Reload Nginx
      service: name=nginx state=reloaded
